package eventmanagement;


import eventmanagement.Student_Update;
import eventmanagement.Student_Add;
import eventmanagement.MainFrame;
import eventmanagement.Student_Delete;
import eventmanagement.Student_login;
import eventmanagement.View_Commitee;
import eventmanagement.View_Events;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shraddha
 */
public class Teacher_Register extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Register
     */
    public Teacher_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Item_add = new javax.swing.JMenuItem();
        Item_update = new javax.swing.JMenuItem();
        Item_delete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jLabel6.setText("jLabel6");

        jTextField3.setText("jTextField3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEACHER REGISTER");
        setMinimumSize(new java.awt.Dimension(1540, 820));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("WELCOME TO EVENT MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 240, 810, 100);

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Hello Teacher...!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 180, 310, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teachbc.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1540, 770);

        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(374, 100));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11319908-removebg-preview.png"))); // NOI18N
        jMenu1.setText("CREATE COMMITEE");
        jMenu1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N

        Item_add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Item_add.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        Item_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9775776-removebg-preview.png"))); // NOI18N
        Item_add.setText("Add Students");
        Item_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_addActionPerformed(evt);
            }
        });
        jMenu1.add(Item_add);

        Item_update.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Item_update.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        Item_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1048966-removebg-preview.png"))); // NOI18N
        Item_update.setText("Update Students");
        Item_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_updateActionPerformed(evt);
            }
        });
        jMenu1.add(Item_update);

        Item_delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Item_delete.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        Item_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/17188760-removebg-preview.png"))); // NOI18N
        Item_delete.setText("Delete Students");
        Item_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_deleteActionPerformed(evt);
            }
        });
        jMenu1.add(Item_delete);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event.png"))); // NOI18N
        jMenu2.setText("VIEW COMMITEE");
        jMenu2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event.png"))); // NOI18N
        jMenuItem4.setText("View Commitee");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        jMenu3.setText("VIEW EVENTS");
        jMenu3.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        jMenuItem5.setText("View Events");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jMenu4.setText("LOGOUT");
        jMenu4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanagement/home.png"))); // NOI18N
        jMenu5.setText("HOME");
        jMenu5.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_deleteActionPerformed
        // TODO add your handling code here:
        Student_Delete fmDelete = new Student_Delete();
        fmDelete.setVisible(true);
    }//GEN-LAST:event_Item_deleteActionPerformed

    private void Item_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_addActionPerformed
       Student_Add fmAdd = new Student_Add();
       fmAdd.setVisible(true);
    }//GEN-LAST:event_Item_addActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void Item_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_updateActionPerformed
       Student_Update fmUpdate = new Student_Update();
       fmUpdate.setVisible(true);
    }//GEN-LAST:event_Item_updateActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        View_Commitee fm = new View_Commitee();
        fm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       View_Events fmview = new View_Events();
        fmview.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        int a= JOptionPane.showConfirmDialog(null,"Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            Teacher_login g = new Teacher_login();
            g.setVisible(true);
            
        }        
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        MainFrame f = new MainFrame();
        f.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_add;
    private javax.swing.JMenuItem Item_delete;
    private javax.swing.JMenuItem Item_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
